inherit_from: .rubocop_todo.yml

require:
- rubocop-rails
- rubocop-minitest
- rubocop-performance

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
